/**
 * seed-admin.mjs
 *
 * Creates an admin user in Cognito and syncs a User record to DynamoDB.
 *
 * Usage (run from project root, requires Node 18+):
 *   node scripts/seed-admin.mjs
 *
 * Prerequisites:
 *   - amplify_outputs.json in project root (generated by `ampx sandbox`)
 *   - AWS credentials configured (e.g. ampx sandbox must be running)
 *   - @aws-sdk/client-cognito-identity-provider
 *
 * Environment variables (optional overrides):
 *   ADMIN_EMAIL    — default: admin@uplift.local
 *   ADMIN_PASSWORD — default: Admin123!
 *   ADMIN_NAME     — default: Platform Admin
 */

import { readFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { Amplify } from 'aws-amplify';
import { signIn, signOut } from 'aws-amplify/auth';
import { generateClient } from 'aws-amplify/data';
import {
  CognitoIdentityProviderClient,
  AdminCreateUserCommand,
  AdminSetUserPasswordCommand,
  AdminUpdateUserAttributesCommand,
} from '@aws-sdk/client-cognito-identity-provider';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');

// ── Config ───────────────────────────────────────────────────────────────────
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'admin@uplift.local';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'Admin123!';
const ADMIN_NAME = process.env.ADMIN_NAME || 'Platform Admin';

// ── Resolve amplify_outputs.json ─────────────────────────────────────────────
const configPath = join(projectRoot, 'amplify_outputs.json');
if (!existsSync(configPath)) {
  console.error('amplify_outputs.json not found. Run `ampx sandbox` first.');
  process.exit(1);
}

const outputs = JSON.parse(readFileSync(configPath, 'utf-8'));
/** Do not pass `ssr: true` here — that uses cookie storage and breaks sign-in in Node. */
Amplify.configure(outputs);

// Extract Cognito config from outputs
const authConfig = outputs.auth;
if (!authConfig?.user_pool_id || !authConfig?.aws_region) {
  console.error('Could not find Cognito user pool config in amplify_outputs.json');
  process.exit(1);
}

const cognitoClient = new CognitoIdentityProviderClient({
  region: authConfig.aws_region,
});
const userPoolId = authConfig.user_pool_id;

async function main() {
  console.log(`\nCreating admin user: ${ADMIN_EMAIL}`);
  console.log(`User Pool: ${userPoolId}\n`);

  // 1. Create the Cognito user
  try {
    await cognitoClient.send(
      new AdminCreateUserCommand({
        UserPoolId: userPoolId,
        Username: ADMIN_EMAIL,
        UserAttributes: [
          { Name: 'email', Value: ADMIN_EMAIL },
          { Name: 'email_verified', Value: 'true' },
          { Name: 'name', Value: ADMIN_NAME },
          { Name: 'custom:role', Value: 'ADMIN' },
        ],
        MessageAction: 'SUPPRESS', // Don't send welcome email
      })
    );
    console.log('✅ Cognito user created');
  } catch (err) {
    if (err.name === 'UsernameExistsException') {
      console.log('ℹ️  Cognito user already exists, updating attributes...');
    } else {
      throw err;
    }
  }

  // 2. Set permanent password (skip FORCE_CHANGE_PASSWORD state)
  try {
    await cognitoClient.send(
      new AdminSetUserPasswordCommand({
        UserPoolId: userPoolId,
        Username: ADMIN_EMAIL,
        Password: ADMIN_PASSWORD,
        Permanent: true,
      })
    );
    console.log('✅ Password set');
  } catch (err) {
    console.error('❌ Failed to set password:', err.message);
    throw err;
  }

  // 3. Ensure custom:role is ADMIN
  try {
    await cognitoClient.send(
      new AdminUpdateUserAttributesCommand({
        UserPoolId: userPoolId,
        Username: ADMIN_EMAIL,
        UserAttributes: [
          { Name: 'custom:role', Value: 'ADMIN' },
        ],
      })
    );
    console.log('✅ custom:role set to ADMIN');
  } catch (err) {
    console.error('❌ Failed to set custom:role:', err.message);
  }

  // 4. Sync User record to DynamoDB (owner-only create — sign in with SRP, then userPool GraphQL)
  try {
    await signIn({ username: ADMIN_EMAIL, password: ADMIN_PASSWORD });
    const client = generateClient();
    const { data, errors } = await client.graphql({
      query: `
        mutation CreateUser($input: CreateUserInput!) {
          createUser(input: $input) {
            id
            name
            email
            role
          }
        }
      `,
      variables: {
        input: {
          name: ADMIN_NAME,
          email: ADMIN_EMAIL,
          role: 'ADMIN',
        },
      },
      authMode: 'userPool',
    });

    if (errors?.length) {
      const msg = errors[0]?.message ?? '';
      if (msg.includes('ConditionalCheckFailed') || /duplicate/i.test(msg)) {
        console.log('ℹ️  User record already exists in DynamoDB');
      } else {
        console.warn('⚠️  GraphQL errors:', msg);
      }
    } else {
      console.log('✅ User record created in DynamoDB:', data?.createUser?.id);
    }
  } catch (err) {
    const msg = err?.message ?? String(err);
    if (msg.includes('ConditionalCheckFailedException') || msg.includes('already exists')) {
      console.log('ℹ️  User record already exists in DynamoDB');
    } else {
      console.warn('⚠️  Could not sync User record to DynamoDB:', msg);
    }
  } finally {
    try {
      await signOut();
    } catch {
      /* ignore */
    }
  }

  console.log('\n🎉 Admin user ready!');
  console.log(`   Email:    ${ADMIN_EMAIL}`);
  console.log(`   Password: ${ADMIN_PASSWORD}`);
  console.log(`   Role:     ADMIN\n`);
}

main().catch((err) => {
  console.error('❌ Fatal error:', err);
  process.exit(1);
});
